EmployeeDirectory/Controllers/EmployeeAdminUserController.cs
using EmployeeDirectory.Business;
using EmployeeDirectory.Entity;
using EmployeeDirectory.Helper;
using EmployeeDirectory.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeDirectory.Controllers
{
    public class EmployeeAdminUserController : BaseController
    {

        [Authorization(ScreenAlias.EmployeeAdminUser, Rights.View, true)]
        public ActionResult EmployeeDirectoryAdminUserList()
        {
            List<AdminUserEntity> adminUserList = new List<AdminUserEntity>();

            var permission = CommonMethods.CheckPermission(StringEnum.GetStringValue(ScreenAlias.EmployeeAdminUser));
            if (permission != null)
            {
                ViewBag.IsAdd = CommonMethods.GetFormPermission(permission).IsAdd;
                ViewBag.IsEdit = CommonMethods.GetFormPermission(permission).IsEdit;
                ViewBag.IsDelete = CommonMethods.GetFormPermission(permission).IsDelete;
            }

            adminUserList = new UserBusiness().GetEmployeeDirectoryUserList();
            return View(adminUserList);
        }


        [Authorization(ScreenAlias.EmployeeAdminUser, Rights.Add, true)]
        public ActionResult CreateEmpAdminUser()
        {
            List<GroupMasterEntity> lstGroupMasterEntity = new List<GroupMasterEntity>();
            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
            List<SelectListItem> idGroupMaster = new List<SelectListItem>();
            AdminUserModel model = new AdminUserModel();

            idGroupMaster.Add(new SelectListItem() { Text = "select", Value = "0" });
            lstGroupMasterEntity = objGroupMasterBusiness.GetAllGroupMasterList();

            foreach (GroupMasterEntity objGroupMasterEntity in lstGroupMasterEntity)
            {
                idGroupMaster.Add(new SelectListItem() { Text = objGroupMasterEntity.Name, Value = Convert.ToString(objGroupMasterEntity.ID) });
            }

            var UserTypeList = new List<SelectListItem>() 
            { new SelectListItem() { Text = "Select", Value = "" },
              new SelectListItem() { Text = "Employee Directory", Value = "3" } 
            };
            ViewBag.UserTypeList = UserTypeList;
            ViewBag.GroupMasterList = idGroupMaster;
            return View();
        }


        [HttpPost]
        public ActionResult CreateEmpAdminUser(AdminUserModel model)
        {
            //Mapper.CreateMap<AdminUserModel, AdminUserEntity>();
            //AdminUserEntity entity = Mapper.Map<AdminUserModel, AdminUserEntity>(model);
            if (!new UserBusiness().CheckEmpUserAlreadyExists(model.UserName.Trim()))
            {
                AdminUserEntity entity = new AdminUserEntity();
                entity.UserName = model.UserName.Trim();
                entity.FirstName = model.FirstName.Trim();
                entity.LastName = model.LastName.Trim();
                entity.Email = model.Email.Trim();
                entity.UserType = model.UserType;
                entity.GroupId = model.GroupId;
                //entity.Password = MD5Helper.Utf8MD5Hex(model.Password);
                int result = new UserBusiness().SaveAdminUser(entity);
                if (result > 0)
                {
                    return RedirectToAction("EmployeeDirectoryAdminUserList");
                }
                ViewBag.ErrorMessage = "An Error occured while processing your request.";
            }
            else
            {
                List<GroupMasterEntity> lstGroupMasterEntity = new List<GroupMasterEntity>();
                GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
                List<SelectListItem> idGroupMaster = new List<SelectListItem>();

                var UserTypeList = new List<SelectListItem>() {new SelectListItem() { Text = "Employee Directory", Value = UserType.EmployeeDirectory.ToString() } 
                                                      };
                lstGroupMasterEntity = objGroupMasterBusiness.GetAllGroupMasterList();

                foreach (GroupMasterEntity objGroupMasterEntity in lstGroupMasterEntity)
                {
                    idGroupMaster.Add(new SelectListItem() { Text = objGroupMasterEntity.Name, Value = Convert.ToString(objGroupMasterEntity.ID) });
                }
                ViewBag.GroupMasterList = idGroupMaster;
                ViewBag.UserTypeList = UserTypeList;
                ViewBag.ErrorMessage = "User Already Exists";

            }

            return View();
        }


        [Authorization(ScreenAlias.EmployeeAdminUser, Rights.Edit, true)]
        public ActionResult EditEmpAdminUser(int ID)
        {
            List<GroupMasterEntity> lstGroupMasterEntity = new List<GroupMasterEntity>();
            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
            AdminUserEntity entity = new UserBusiness().GetAdminUserDetailById(ID);
            List<SelectListItem> idGroupMaster = new List<SelectListItem>();
            idGroupMaster.Add(new SelectListItem() { Text = "select", Value = "0" });
            AdminUserModel model = new AdminUserModel();

            lstGroupMasterEntity = objGroupMasterBusiness.GetAllGroupMasterList();

            foreach (GroupMasterEntity objGroupMasterEntity in lstGroupMasterEntity)
            {
                idGroupMaster.Add(new SelectListItem() { Text = objGroupMasterEntity.Name, Value = Convert.ToString(objGroupMasterEntity.ID) });
            }

            model.UserName = entity.UserName;
            model.FirstName = entity.FirstName;
            model.LastName = entity.LastName;
            model.Email = entity.Email;
            model.UserType = entity.UserType;
            model.IsLocked = entity.IsLocked;
            model.GroupId = entity.GroupId;
            var UserTypeList = new List<SelectListItem>() { 
                                                               new SelectListItem() { Text = "Employee Directory", Value = "3" } 
                                                      };
            ViewBag.UserTypeList = UserTypeList;
            ViewBag.GroupMasterList = idGroupMaster;
            return View(model);
        }


        [HttpPost]
        public ActionResult EditEmpAdminUser(AdminUserModel model)
        {
            AdminUserEntity entity = new AdminUserEntity();
            entity.ID = model.ID;
            entity.UserName = model.UserName;
            entity.FirstName = model.FirstName;
            entity.LastName = model.LastName;
            entity.Email = model.Email;
            entity.UserType = model.UserType;
            entity.GroupId = model.GroupId;
            entity.UpdatedBy = Convert.ToInt32(Session[AppConstant.USERID]);
            entity.IsLocked = model.IsLocked;
            entity.UpdatedDate = DateTime.Now;



            int result = new UserBusiness().UpdateAdminUser(entity);
            if (result > 0)
            {
                return RedirectToAction("EmployeeDirectoryAdminUserList");
            }
            ViewBag.status = "An Error occured while processing your request.";
            return View();
        }

        [Authorization(ScreenAlias.EmployeeAdminUser, Rights.Delete, true)]
        public ActionResult DeleteEmpAdminUser(int ID)
        {
            int result = new UserBusiness().DeleteAdminUser(ID);
            if (result > 0)
            {
                return RedirectToAction("EmployeeDirectoryAdminUserList");
            }
            ViewBag.status = "An Error occured while processing your request.";
            return View();
        }




    }
}

EmployeeDirectory/Views/EmployeeAdminUser/CreateEmpAdminUser.cshtml
@model EmployeeDirectory.Models.AdminUserModel

@{
    ViewBag.Title = "CreateAdminUser";
}

<div class="container-fluid">
    <br />
    @if (ViewBag.ErrorMessage != "" && ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger">
            @ViewBag.ErrorMessage
        </div>
    }

    @using (Html.BeginForm("CreateEmpAdminUser", "EmployeeAdminUser", FormMethod.Post, new { @id = "EmployeeAdminUserForm", enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
    
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header" style="margin-bottom:20px;">
                        <h3 class="box-title">Add User</h3>
                    </div>
                    <div class="box-body">
                        <div class="col-md-12">

                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">User Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.HiddenFor(m => m.ID)
                                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", @placeholder = "User Name", onblur = "UpdateEmailId(this);" })
                                </div>
                            </div>@*
                <div class="form-group">
                    <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Password</label>
                    <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">ReType Password</label>
                    <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "ReType Password" })
                    </div>
                </div>*@
                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">First Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder = "First Name" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Last Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "Last Name" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Email <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email ID" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">User Type</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.DropDownListFor(m => m.UserType, ViewBag.UserTypeList as List<SelectListItem>, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Group Name</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.DropDownListFor(m => m.GroupId, ViewBag.GroupMasterList as List<SelectListItem>, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">&nbsp;</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-6">
                                    <div class="checkbox">
                                        <label>
                                            @Html.CheckBoxFor(m => m.IsLocked, new { @class = "checkbox" })Is Locked?
                                        </label>
                                    </div>
                                </div>
                            </div>
                          

                        </div>
                    </div>

                    <div class="footer-header">
                        <div class="col-xs-12">

                            @Html.HiddenFor(m => m.ID)
                            <div class="col-xs-4 pull-right">
                                <button type="submit" class="col-xs-6 btneffect pull-right">Submit</button>
                                <a title="" href="~/EmployeeAdminUser/EmployeeDirectoryAdminUserList" class="col-xs-6 btneffect pull-right">Back</a>
                            </div>
                        </div>
                    </div>

                            
                        </div>
                    </div>
                </div>
    }
    </div>
<script>

    function UpdateEmailId(ctl) {
        $('#Email').val(ctl.value + "@@hcsgcorp.com");
    }
</script>

EmployeeDirectory/Views/EmployeeAdminUser/EditEmpAdminUser.cshtml
@model EmployeeDirectory.Models.AdminUserModel

@{
    ViewBag.Title = "EditAdminUser";
}

<div class="container-fluid">
    <br />
    @if (ViewBag.ErrorMessage != "" && ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger">
            @ViewBag.ErrorMessage
        </div>
    }

    @using (Html.BeginForm("EditEmpAdminUser", "EmployeeAdminUser", FormMethod.Post, new { @id = "EmployeeAdminUserForm", enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header" style="margin-bottom:20px;">
                        <h3 class="box-title">Edit User</h3>
                    </div>
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">User Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.HiddenFor(m => m.ID)
                                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", @placeholder = "User Name", @readonly = "readonly" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">First Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder = "First Name" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Last Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "Last Name" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Email <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email ID" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">User Type <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-3">
                                    @Html.DropDownListFor(m => m.UserType, ViewBag.UserTypeList as List<SelectListItem>, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Group Name</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.DropDownListFor(m => m.GroupId, ViewBag.GroupMasterList as List<SelectListItem>, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">&nbsp;</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-6">
                                    <div class="checkbox">
                                        <label>
                                            @Html.CheckBoxFor(m => m.IsLocked, new { @class = "checkbox" })Is Locked?
                                        </label>
                                    </div>
                                </div>
                            </div>



                        </div>

                    </div>

                    <div class="footer-header">
                        <div class="col-xs-12">

                            @Html.HiddenFor(m => m.ID)
                            <div class="col-xs-4 pull-right">
                                
                                
                                    <button type="submit" class="col-xs-6 btneffect pull-right">Update</button>
                                
                                <a class="col-xs-6 btneffect pull-right" href="~/EmployeeAdminUser/EmployeeDirectoryAdminUserList">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>




EmployeeDirectory/Views/EmployeeAdminUser/EmployeeDirectoryAdminUserList.cshtml
@model List<EmployeeDirectory.Entity.AdminUserEntity>

@{
    ViewBag.Title = "AdminUserList";
}




<div class="container-fluid">
    <br />
    <div class="row">
        <div class="box-header">
            <div class="col-sm-5 col-xs-12">
                <h3 class="box-title">  AdminUser List</h3>
            </div>
            @*@if (Convert.ToString(Session[EmployeeDirectory.Entity.AppConstant.USERTYPE]) == Convert.ToString(EmployeeDirectory.Entity.UserType.SuperUser))*@
            @if (ViewBag.IsAdd != null)
            {
                if (ViewBag.IsAdd)
                {
                    <div class="col-sm-7 col-xs-12">
                        <a class="pull-right btneffect AdminUserAdd" style="margin-right: 10px; margin-top: 16px !important;" href="~/EmployeeAdminUser/CreateEmpAdminUser">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Create User
                        </a>
                    </div>
                }
            }
        </div>

        <div class="container-fluid">
            <div class="row">
                <form role="form" id="AdminUserList" class="form-horizontal">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                        <div class="form-group">
                            <div class="table-responsive" id="divAdminUserList">
                                @Html.Partial("_EmpAdminUserWebGrid", Model)
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

EmployeeDirectory/Views/EmployeeAdminUser/_EmpAdminUserWebGrid.cshtml
@model List<EmployeeDirectory.Entity.AdminUserEntity>

@{
    Layout = null;
}
@{
    var gdAdminUserList = new WebGrid(Model, canPage: true, canSort: false, rowsPerPage: EmployeeDirectory.Helper.ConfigurationProvider.WegGridPageSize, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
}
@if (Model.Count() > 0)
{
    <div>
        @gdAdminUserList.GetHtml(tableStyle: "table table-bordered table-hover table-striped",
                mode: WebGridPagerModes.Numeric,
                htmlAttributes: new { Id = "tblAdminUserList" },
                columns: gdAdminUserList.Columns(
                gdAdminUserList.Column("UserName", "UserName"),
                gdAdminUserList.Column("FirstName", "First Name"),
                gdAdminUserList.Column("LastName", "Last Name"),
                gdAdminUserList.Column("IsLocked", "IsLocked"),
                gdAdminUserList.Column(null, "Action", format: @<text>
                    @if (ViewBag.IsEdit != null)
                    {
                        if (ViewBag.IsEdit)
                        {
                            <a href="~/EmployeeAdminUser/EditEmpAdminUser/@item.ID"><i class="fa fa-edit"></i></a>
                        }
                    }
                    @if (ViewBag.IsDelete != null)
                    {
                        if (ViewBag.IsDelete)
                        {
                            <a href="~/EmployeeAdminUser/DeleteEmpAdminUser/@item.ID"><i class="fa fa-trash"></i></a>
                        }
                    }
                </text>, style: "webgrid-action-column")
                                                                                             ))
    </div>
}
<script>
    $(document).ready(function () {

        @*var allheader = $('#tblAdminUserList th')
        for (var a = 0; a < allheader.length; a++) {
            var header = allheader[a];
            var headertext = allheader[a].innerHTML.trim();
            var USERTYPE = String('@Session[EmployeeDirectory.Entity.AppConstant.USERTYPE]');
            var su = String('@EmployeeDirectory.Entity.UserType.SuperUser');

            if (USERTYPE != su) {
                if (headertext == 'Action') {
                    header.setAttribute('class', 'headerhide');
                    //"webgrid-action-column
                }

            }

        }
        if (USERTYPE != su) {
            $('#tblAdminUserList tr').find('td.webgrid-action-column').attr('class', 'headerhide');
        }*@
    });


</script>