EmployeeDirectory/Controllers/GroupMasterController.cs
using EmployeeDirectory.Business;
using EmployeeDirectory.Entity;
using EmployeeDirectory.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeDirectory.Controllers
{
    public class GroupMasterController : BaseController
    {
        [Authorization(ScreenAlias.GroupMaster, Rights.View, true)]
        public ActionResult GroupMasterList()
        {
            
            var permission = CommonMethods.CheckPermission(StringEnum.GetStringValue(ScreenAlias.GroupMaster));
            if (permission != null)
            {
                ViewBag.IsAdd = CommonMethods.GetFormPermission(permission).IsAdd;
                ViewBag.IsEdit = CommonMethods.GetFormPermission(permission).IsEdit;
                ViewBag.IsDelete = CommonMethods.GetFormPermission(permission).IsDelete;
            }


            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
            GroupMasterEntity objGroupMasterEntity = new GroupMasterEntity();
            int[] paggingArray = Helper.HelperCls.GetDisplayRecordCount(ConfigurationProvider.Pageindex, ConfigurationProvider.WegGridPageSize);
            List<GroupMasterEntity> list = objGroupMasterBusiness.GetGroupMasterDetailList("", "", paggingArray[0], paggingArray[1], "", "");
            for (int i = 0; i < list.Count; i++)
            {
                list[i].Pageindex = Convert.ToInt32(ConfigurationProvider.Pageindex);
            }

            objGroupMasterEntity.GroupMasterEntityList = list;
            ViewBag.DivRegDistList = new List<DivRegDistEntity>();
            return View(objGroupMasterEntity);
        }

        public ActionResult GroupMasterListPagingWise(string pageindex, string pagesize, string columnName, string sortorder)
        {

            GroupMasterEntity objGroupMasterEntity = new GroupMasterEntity();
            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();

            objGroupMasterEntity.Pageindex = Convert.ToInt32(pageindex);
            objGroupMasterEntity.pagesize = Convert.ToInt32(pagesize);

            int[] paggingArray = Helper.HelperCls.GetDisplayRecordCount(ConfigurationProvider.Pageindex, ConfigurationProvider.WegGridPageSize);
            List<GroupMasterEntity> list = objGroupMasterBusiness.GetGroupMasterDetailList("", "", paggingArray[0], paggingArray[1], "", "");

            //for (int i = 0; i < list.Count; i++)
            //{
            //    list[i].Pageindex = Convert.ToInt32(ConfigurationProvider.Pageindex);
            //}
            ViewBag.PageSize = int.Parse(pagesize);
            return PartialView("_GroupMasterList", list);
        }


        [HttpPost]
        public ActionResult SaveGroupMaster(GroupMasterEntity model) {

            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
            int ans = 0;
            try
            {
                //model.UserId = SessionManager.UserID;
                //model.UserName = SessionManager.UserName;
                ans = objGroupMasterBusiness.SaveGroupMaster(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while processing your request. Please try again later";
            }
            return RedirectToAction("GroupMasterList");
        }

        [Authorization(ScreenAlias.GroupMaster, Rights.Edit, true)]
        public ActionResult EditGroupMaster(int ID) {

            GroupMasterEntity objGroupMasterEntity = new GroupMasterEntity();
            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
            try
            {

                objGroupMasterEntity = objGroupMasterBusiness.GetGroupDetailById(ID);

            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while processing your request. Please try again later";
            }

            return View(objGroupMasterEntity);
        }

        [Authorization(ScreenAlias.GroupMaster, Rights.Delete, true)]
        public ActionResult DeleteGroupMaster(int ID)
        {

            GroupMasterEntity objGroupMasterEntity = new GroupMasterEntity();
            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
            try
            {

                int ans = objGroupMasterBusiness.DeleteGroupMaster(ID);

            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while processing your request. Please try again later";
            }

            return RedirectToAction("GroupMasterList");
        }

        public ActionResult GetAllGroupMasterList()
        {

            GroupMasterEntity objGroupMasterEntity = new GroupMasterEntity();
            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
            try
            {
                objGroupMasterEntity.GroupMasterEntityList = objGroupMasterBusiness.GetAllGroupMasterList();

            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while processing your request. Please try again later";
            }

            return Json(objGroupMasterEntity.GroupMasterEntityList, JsonRequestBehavior.AllowGet);
        }



    }
}

EmployeeDirectory/Views/GroupMaster/EditGroupMaster.cshtml
@model EmployeeDirectory.Entity.GroupMasterEntity

@{
    Layout = null;
}

<!DOCTYPE html>

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Edit Group</h4>
        </div>
        @using (Html.BeginForm("SaveGroupMaster", "GroupMaster", FormMethod.Post, new { @id = "FormGroupMaster", @class = "validation-form-container row-fluid form-horizontal" }))
        {
            @Html.ValidationSummary(true)
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Name <span style="color:red;">*</span></label>
                        <div class="col-sm-9 control-label">
                            @Html.TextBoxFor(m => m.Name, new { @style = "float: left;" })
                            @Html.ValidationMessageFor(m => m.Name)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Description</label>
                        <div class="col-sm-9 control-label">
                            @Html.TextAreaFor(m => m.Description, new { @style = "float: left;" })
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Is Active?</label>
                        <div class="col-sm-1 control-label">
                            @Html.CheckBoxFor(m => m.IsActive, new { @style = "float: left;" })
                        </div>
                    </div>

                </div>

            </div>
            <div class="modal-footer">
                @Html.HiddenFor(m=>m.ID)
                <button type="submit" class="btneffect pull-right">Update</button>
                <button type="button" class="btneffect pull-right" data-dismiss="modal">Close</button>
                <input type="hidden" id="trindex" />
            </div>
        }
    </div>
</div>

EmployeeDirectory/Views/GroupMaster/GroupMasterList.cshtml
@model EmployeeDirectory.Entity.GroupMasterEntity

@{
    ViewBag.Title = "GroupMasterList";
}



<div class="container-fluid">
    <br />
    <div class="row">
        <div class="box-header">
            <div class="col-sm-5 col-xs-12">
                <h3 class="box-title">  Group List</h3>
            </div>
            @if (ViewBag.IsAdd != null)
            {
                if (ViewBag.IsAdd)
                {

                    <div class="col-sm-7 col-xs-12">
                        <a class="pull-right btneffect AdminUserAdd" id="btnAddGroupMaster" onclick="AddGroupMaster()" name="Add">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Add
                        </a>
                    </div>
                }
            }
        </div>

        <div class="container-fluid">
            <div class="row">
                <form role="form" id="AdminUserList" class="form-horizontal">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                        <div class="form-group">
                            <div class="table-responsive" id="divUserList">
                                @Html.Partial("_GroupMasterList", Model.GroupMasterEntityList)
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>


<div class="modal-dialog" id="AdditionalDialog" style="display:none;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Add Group</h4>
        </div>
        @using (Html.BeginForm("SaveGroupMaster", "GroupMaster", FormMethod.Post, new { @id = "FormGroupMaster", @class = "validation-form-container row-fluid form-horizontal" }))
        {
            @Html.ValidationSummary(true)
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Name <span style="color:red;">*</span></label>
                        <div class="col-sm-9 control-label">
                            @Html.TextBoxFor(m => m.Name, new { @style = "float: left;" })
                            @Html.ValidationMessageFor(m => m.Name)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Description</label>
                        <div class="col-sm-9 control-label">
                            @Html.TextAreaFor(m => m.Description, new { @style = "float: left;" })
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Is Active?</label>
                        <div class="col-sm-1 control-label">
                            @Html.CheckBoxFor(m => m.IsActive, new { @style = "float: left;" })
                        </div>
                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btneffect pull-right ladda-button">Save</button>
                <button type="button" class="btneffect pull-right ladda-button" data-dismiss="modal">Close</button>
                <input type="hidden" id="trindex" />
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        //$.validator.unobtrusive.parse("FormGroupMaster");
        $('#FormGroupMaster').find('#IsActive').attr('checked', true);
    })


    function AddGroupMaster() {
        $("#parentModal").html($("#AdditionalDialog").clone().show()).modal('show');
    }


    $('#FormGroupMaster').live('submit', function () {

        var Name = $(this).find('#Name').val().trim();

        if (Name == '') {
            $(this).find('#Name').css('border', 'red 1px solid');
            return false;

        }



    });
</script>

EmployeeDirectory/Views/GroupMaster/_GroupMasterList.cshtml
@model List<EmployeeDirectory.Entity.GroupMasterEntity>

@{
    var gdGroupList = new WebGrid(Model, canPage: false, canSort: false, rowsPerPage: 10, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
}

<div>
    @gdGroupList.GetHtml(tableStyle: "webgrid",
                headerStyle: "webgrid-header",
                footerStyle: "webgrid-footer",
                htmlAttributes: new { Id = "tblUserList" },
                alternatingRowStyle: "webgrid-alternating-row",
                selectedRowStyle: "webgrid-selected-row",
                rowStyle: "webgrid-row-style",
                mode: WebGridPagerModes.Numeric,
                        columns: gdGroupList.Columns(
                        gdGroupList.Column("Name", "Group Name"),
                        gdGroupList.Column("Description", "Description"),
                        gdGroupList.Column("Action", format: @<text>
                            @if (ViewBag.IsEdit != null)
                            {
                                if (ViewBag.IsEdit)
                                {

                                    <a href="#" onclick="EditGroupMaster(@item.ID)"><i class="fa fa-edit"></i></a>
                                }
                            }
                            @if (ViewBag.IsDelete != null)
                            {
                                if (ViewBag.IsDelete)
                                {
                                    <a href="~/GroupMaster/DeleteGroupMaster/@item.ID" onclick="return confirm('Are you sure you wish to delete this Group?');"><i class="fa fa-trash"></i></a>
                                }
                            }
                        </text>, style: "webgrid-action-column")))

</div>

<input type="hidden" id="hdnTotalRecord" value="@Model[0].TotalRecord" />
<input type="hidden" id="hdnPageIndex" value="@Model[0].Pageindex" />

<script>

    $(document).ready(function () {

      //  GeneratePagingFooter();

    });

    function EditGroupMaster(me) {

        var Liveurl = '@System.Configuration.ConfigurationManager.AppSettings["LivesubURL"]';
        Liveurl = "/" + Liveurl + "GroupMaster/EditGroupMaster";
        $("#modalWindow,#ui-loader").show();
        $.ajax({
            url: Liveurl,
            type: "GET",
            data: { Id: me },
            success: function (result) {
                $("#parentModal").html(result).modal('show');
                $("#modalWindow,#ui-loader").hide();
            }
        });
    }

    function GeneratePagingFooter() {
        
        var Liveurl = '@System.Configuration.ConfigurationManager.AppSettings["LivesubURL"]';
        var TotalRecord = $("#hdnTotalRecord").val();
        var PageIndex = $("#hdnPageIndex").val();
        var allheader = $('#tblEmployeeDirectoryList th');
        for (var a = 0; a < allheader.length; a++) {
            var header = allheader[a];
            var headertext = allheader[a].innerHTML.trim();
            if (headertext != 'Action') {
                allheader[a].innerHTML = '';
                var createA = document.createElement('a');
                var createAText = document.createTextNode(headertext);
                createA.setAttribute('href', "#");
                createA.setAttribute('onclick', "Sorting('" + headertext + "');");
                createA.appendChild(createAText);
                header.appendChild(createA);
            }
            if (headertext == 'TotalRecord') {
                header.setAttribute('class', 'headerhide');
            }
            if (headertext == 'Pageindex') {
                header.setAttribute('class', 'headerhide');
            }
        }

        var Pagesize = 5; @*'@EmployeeDirectory.Helper.ConfigurationProvider.WegGridPageSize';*@
        if ($("#hdnTotalRecord").val()) {
            var text = "<tr class='webgrid-footer'><td colspan='15'>";
            text = text + " <div class='topheader' id='divpagging'><div style='width: 100%;' class='classClear tdRepeaterFooter'>";
            text = text + "<div class='repeaterFooterLeft' style='width: 40%'> Page <label id='lblPageindex'></label> of <label id='lblMaxpage'></label> (Total Records: <label id='lblTotalRecord'></label>)</div>";
            text = text + "<div class='repeaterFooterCenter' style='width: 20%'>";
            text = text + "<a href='#' id='first'><img src='" + "/" + Liveurl + "img/FirstButton.gif' /></a>";
            text = text + "<a href='#' id='Previous'><img src='" + "/" + Liveurl + "img/PreviousButton.gif' /></a>";
            text = text + "<a href='#' id='Next'><img src='" + "/" + Liveurl + "img/NextButton.gif' /></a>";
            text = text + "<a href='#' id='Last'><img src='" + "/" + Liveurl + "img/LastButton.gif' /></a></div>";
            text = text + "<div class='repeaterFooterRight'><div class='divTextL'>Go To Page No</div>";
            text = text + "<div class='divTextBoxM'><input type='text' id='txtGO' class='form-control' onkeypress='return IntegerValidation(event,this,8);' style='width:50px !important; height:23px !important; margin: 0 0 0 0 !important; ' /></div>";
            text = text + "<div class='divButtonR'><a href='#' id='go'><img src='" + "/" + Liveurl + "img/GoButton.gif' /></a></div></div></div></div>";
            text = text + "</td></tr>";
            $('#tblUserList tbody').append(text);
            $("#lblPageindex").text(PageIndex);
            $("#lblTotalRecord").text(TotalRecord);
            var MaxPage = parseInt((TotalRecord == 0) ? 0 : ((TotalRecord % Pagesize == 0) ? (TotalRecord / Pagesize) : parseInt((TotalRecord / Pagesize)) + 1));
            $("#lblMaxpage").text(MaxPage);
        }
    }


    $('div #divpagging a').click(function () {
        var Command = $(this).attr('id');
        var PageNo = $("#txtGO").val();
        var Pageindex = $("#lblPageindex").text();
        var MaxPage = $("#lblMaxpage").text();
        var totalRecord = $("#lblTotalRecord").text();
        var Sortorder = $("#hdnSortOrder").text();
        var SortColumn = $("#hdnSortColumn").text();

        if (Command == 'first') {
            $("#lblPageindex").text("1");
        }
        else if (Command == 'Previous') {

            $("#lblPageindex").text((parseInt($("#lblPageindex").text()) - 1).toString());
            if (parseInt($("#lblPageindex").text()) <= 0) {
                $("#lblPageindex").text("1");
            }
        }
        else if (Command == 'Next') {
            $("#lblPageindex").text((parseInt($("#lblPageindex").text()) + 1).toString());
            if (parseInt($("#lblPageindex").text()) >= parseInt($("#lblMaxpage").text())) {
                $("#lblPageindex").text($("#lblMaxpage").text());
            }
        }
        else if (Command == 'Last') {
            $("#lblPageindex").text($("#lblMaxpage").text());
        }
        else if (Command == "go") {
            if (PageNo != "") {
                $("#lblPageindex").text((parseInt(PageNo)).toString());
                if (parseInt($("#lblPageindex").text()) <= 0) {
                    $("#lblPageindex").text("1");
                }
                else if (parseInt($("#lblPageindex").text()) >= parseInt($("#lblMaxpage").text())) {
                    $("#lblPageindex").text($("#lblMaxpage").text());
                }
            }
        }

        var pagesize = $("#ddlpagesize").val();
        if (pagesize == "" || pagesize == undefined || pagesize == "0") {
            pagesize = '@System.Configuration.ConfigurationManager.AppSettings["PageSize"]';
        }

        Pageindex = $("#lblPageindex").text();
        var Liveurl = '@System.Configuration.ConfigurationManager.AppSettings["LivesubURL"]';
        Liveurl = "/" + Liveurl + "GroupMaster/GroupMasterListPagingWise?Pageindex=" + Pageindex + "&pagesize=" + pagesize + "&columnName=" + SortColumn + "&sortOrder=" + Sortorder;
        $("#modalWindow,#ui-loader").show();
        $.ajax({
            type: "GET",
            contentType: "application/x-www-form-urlencoded",
            traditional: true,
            url: Liveurl,
            dataType: "html",
            success: function (data) {
                $("#divUserList").html('');
                $("#divUserList").html(data + "&nbsp;");
                $("#modalWindow,#ui-loader").hide();
            }
        });
    });

</script>
