EmployeeDirectory/Controllers/AdminUserController.cs
using EmployeeDirectory.Business;
using EmployeeDirectory.Entity;
using EmployeeDirectory.Helper;
using EmployeeDirectory.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeDirectory.Controllers
{
    public class AdminUserController : BaseController
    {
        /// <summary>
        /// Admins the user list.
        /// </summary>
        /// <returns></returns>
        [Authorization(ScreenAlias.AdminUser, Rights.View, true)]
        public ActionResult AdminUserList()
        {
            List<AdminUserEntity> adminUserList = new List<AdminUserEntity>();
            List<SelectListItem> idUserTypeList = new List<SelectListItem>();
            List<UserTypeEntity> lstUserTypeEntity = new List<UserTypeEntity>();
            UserBusiness objUserBusiness = new UserBusiness();

            var permission = CommonMethods.CheckPermission(StringEnum.GetStringValue(ScreenAlias.AdminUser));
            if (permission != null)
            {
                ViewBag.IsAdd = CommonMethods.GetFormPermission(permission).IsAdd;
                ViewBag.IsEdit = CommonMethods.GetFormPermission(permission).IsEdit;
                ViewBag.IsDelete = CommonMethods.GetFormPermission(permission).IsDelete;
            }
            lstUserTypeEntity = objUserBusiness.GetAllUserTypeList();
            foreach (UserTypeEntity UserTypeEntity in lstUserTypeEntity)
            {
                idUserTypeList.Add(new SelectListItem() { Text = UserTypeEntity.Name, Value = Convert.ToString(UserTypeEntity.ID) });
            }
            int[] paggingArray = Helper.HelperCls.GetDisplayRecordCount(ConfigurationProvider.Pageindex, ConfigurationProvider.WegGridPageSize);
            adminUserList = new UserBusiness().GetAdminUserList("", "", "", "", paggingArray[0], paggingArray[1], "", "");
            for (int i = 0; i < adminUserList.Count; i++)
            {
                adminUserList[i].Pageindex = Convert.ToInt32(ConfigurationProvider.Pageindex);
            }
            ViewBag.UserTypeList = idUserTypeList;

            return View(adminUserList);
        }

        public ActionResult AdminUserListPagingSortingList(string firstName, string lastName, string username, string UserType, string pagesize, string pageindex, string columnName, string sortorder)
        {
            var permission = CommonMethods.CheckPermission(StringEnum.GetStringValue(ScreenAlias.AdminUser));
            if (permission != null)
            {
                ViewBag.IsAdd = CommonMethods.GetFormPermission(permission).IsAdd;
                ViewBag.IsEdit = CommonMethods.GetFormPermission(permission).IsEdit;
                ViewBag.IsDelete = CommonMethods.GetFormPermission(permission).IsDelete;
            }

            UserBusiness objUserBusiness = new UserBusiness();
            if (string.IsNullOrEmpty(pageindex))
            {
                pageindex = "1";
            }

            int[] paggingArray = Helper.HelperCls.GetDisplayRecordCount(Convert.ToInt32(pageindex), int.Parse(pagesize));
            List<AdminUserEntity> list = objUserBusiness.GetAdminUserList(firstName, lastName, username, UserType, paggingArray[0], paggingArray[1], columnName, sortorder);
            for (int i = 0; i < list.Count; i++)
            {
                list[i].Pageindex = Convert.ToInt32(pageindex);
            }

            ViewBag.PageSize = int.Parse(pagesize);
            return PartialView("_AdminUserWebGrid", list);
        }

        /// <summary>
        /// Creates the admin user.
        /// </summary>
        /// <returns></returns>
        [Authorization(ScreenAlias.AdminUser, Rights.Add, true)]
        public ActionResult CreateAdminUser()
        {
            List<GroupMasterEntity> lstGroupMasterEntity = new List<GroupMasterEntity>();
            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
            List<SelectListItem> idGroupMaster = new List<SelectListItem>();
            AdminUserModel model = new AdminUserModel();
            List<UserTypeEntity> lstUserTypeEntity = new List<UserTypeEntity>();
            UserBusiness objUserBusiness = new UserBusiness();
            List<SelectListItem> idUserTypeList = new List<SelectListItem>();

            idGroupMaster.Add(new SelectListItem() { Text = "select", Value = "0" });
            lstGroupMasterEntity = objGroupMasterBusiness.GetAllGroupMasterList();

            foreach (GroupMasterEntity objGroupMasterEntity in lstGroupMasterEntity)
            {
                idGroupMaster.Add(new SelectListItem() { Text = objGroupMasterEntity.Name, Value = Convert.ToString(objGroupMasterEntity.ID) });
            }

            lstUserTypeEntity = objUserBusiness.GetAllUserTypeList();
            foreach (UserTypeEntity UserTypeEntity in lstUserTypeEntity)
            {
                idUserTypeList.Add(new SelectListItem() { Text = UserTypeEntity.Name, Value = Convert.ToString(UserTypeEntity.ID) });
            }

            ViewBag.UserTypeList = idUserTypeList;
            ViewBag.GroupMasterList = idGroupMaster;
            return View();
        }

        /// <summary>
        /// Creates the admin user.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateAdminUser(AdminUserModel model)
        {
            //Mapper.CreateMap<AdminUserModel, AdminUserEntity>();
            //AdminUserEntity entity = Mapper.Map<AdminUserModel, AdminUserEntity>(model);
            try
            {
                if (!new UserBusiness().CheckUserAlreadyExists(model.UserName.Trim()))
                {
                    AdminUserEntity entity = new AdminUserEntity();
                    entity.UserName = model.UserName.Trim();
                    entity.FirstName = model.FirstName.Trim();
                    entity.LastName = model.LastName.Trim();
                    entity.Email = model.Email.Trim();
                    if (model.UserTypeIds != null && model.UserTypeIds.Count() > 0)
                    {
                        entity.UserType = String.Join(",", model.UserTypeIds.ToArray());
                    }
                    entity.GroupId = model.GroupId;
                    entity.IsLocked = model.IsLocked;
                    //entity.Password = MD5Helper.Utf8MD5Hex(model.Password);
                    int result = new UserBusiness().SaveAdminUser(entity);
                    if (result > 0)
                    {
                        return RedirectToAction("AdminUserList");
                    }

                    ViewBag.ErrorMessage = "An Error occured while processing your request.";
                }
                else
                {
                    List<GroupMasterEntity> lstGroupMasterEntity = new List<GroupMasterEntity>();
                    GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
                    List<SelectListItem> idGroupMaster = new List<SelectListItem>();

                    var UserTypeList = new List<SelectListItem>() {new SelectListItem() { Text = "Select", Value = "" },
                                                               new SelectListItem() { Text = "Super User", Value = UserType.SuperUser.ToString() },
                                                               new SelectListItem() { Text = "User", Value = UserType.User.ToString() },
                                                               new SelectListItem() { Text = "Employee Directory", Value = UserType.EmployeeDirectory.ToString() } 
                                                      };
                    lstGroupMasterEntity = objGroupMasterBusiness.GetAllGroupMasterList();

                    foreach (GroupMasterEntity objGroupMasterEntity in lstGroupMasterEntity)
                    {
                        idGroupMaster.Add(new SelectListItem() { Text = objGroupMasterEntity.Name, Value = Convert.ToString(objGroupMasterEntity.ID) });
                    }
                    ViewBag.GroupMasterList = idGroupMaster;
                    ViewBag.UserTypeList = UserTypeList;
                    ViewBag.ErrorMessage = "User Already Exists";


                }
            }
            catch (Exception ex)
            {
                new FieldMasterBusiness().StoreError(ex.Message.ToString());
                throw new Exception("CreateAdminUser Exception :" + ex);
            }


            return View();
        }

        /// <summary>
        /// Edits the admin user.
        /// </summary>
        /// <param name="ID">The identifier.</param>
        /// <returns></returns>
        [Authorization(ScreenAlias.AdminUser, Rights.Edit, true)]
        public ActionResult EditAdminUser(int ID)
        {
            List<GroupMasterEntity> lstGroupMasterEntity = new List<GroupMasterEntity>();
            GroupMasterBusiness objGroupMasterBusiness = new GroupMasterBusiness();
            AdminUserEntity entity = new UserBusiness().GetAdminUserDetailById(ID);
            List<SelectListItem> idGroupMaster = new List<SelectListItem>();
            idGroupMaster.Add(new SelectListItem() { Text = "select", Value = "0" });
            AdminUserModel model = new AdminUserModel();
            List<UserTypeEntity> lstUserTypeEntity = new List<UserTypeEntity>();
            UserBusiness objUserBusiness = new UserBusiness();
            List<SelectListItem> idUserTypeList = new List<SelectListItem>();

            lstGroupMasterEntity = objGroupMasterBusiness.GetAllGroupMasterList();

            foreach (GroupMasterEntity objGroupMasterEntity in lstGroupMasterEntity)
            {

EmployeeDirectory/Views/AdminUser/AdminUserList.cshtml
@model List<EmployeeDirectory.Entity.AdminUserEntity>

@{
    ViewBag.Title = "AdminUserList";
}



@*<script src="~/js/bootstrap-multiselect.js"></script>
<link href="~/css/bootstrap-multiselect.css" rel="stylesheet" />*@

<style>
    .multiselect.dropdown-toggle.btn.btn-default {
        /*margin-right: 5px;*/
        max-width: 130px;
        overflow: hidden;
    }

    .dropdown-menu {
        max-height: 158px;
        overflow: auto;
    }
</style>


<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                <div class="box-header">
                    <div class="col-sm-5 col-xs-12">
                        <h3 class="box-title">  AdminUser List</h3>
                    </div>
                    @*@if (Convert.ToString(Session[EmployeeDirectory.Entity.AppConstant.USERTYPE]) == Convert.ToString(EmployeeDirectory.Entity.UserType.SuperUser))
                        {*@
                    @if (ViewBag.IsAdd != null)
            {
                if (ViewBag.IsAdd)
                {
                    <div class="col-sm-7 col-xs-12">
                        <a class="pull-right btneffect" style="margin-right: 10px; margin-top: 16px !important;" href="~/AdminUser/CreateAdminUser">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Create User
                        </a>
                    </div>
                }
            }
                </div>

                <form role="form" id="AdminUserList" class="form-horizontal">
                    <div class="col-md-12 box-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="txtSearchFirstName" class="col-sm-5 control-label">First Name</label>
                                    <div class="col-sm-7">
                                        <input type="text" id="txtSearchFirstName" name="txtSearchFirstName" class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="txtSearchLastName" class="col-sm-5 control-label">Last Name</label>
                                    <div class="col-sm-7">
                                        <input type="text" id="txtSearchLastName" name="txtSearchLastName" class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="txtSearchUserName" class="col-sm-5 control-label">User Name</label>
                                    <div class="col-sm-7">
                                        <input type="text" id="txtSearchUserName" name="txtSearchUserName" class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3" style="display:none">
                                <div class="form-group">
                                    <label for="inputEmail" class="control-label col-sm-5">User Type</label>
                                    <div class="col-sm-7">
                                        @Html.DropDownList("UserTypeIds", ViewBag.UserTypeList as List<SelectListItem>,"Select", new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix" style="clear: both"></div>

                            <div class="row">
                                <div class="">
                                    <div class="col-md-9">
                                        <div class="form-group">
                                            <label for="txtSearchFirstName" class="col-sm-5 control-label">&nbsp;</label>
                                            <div class="col-sm-7">
                                                &nbsp;
                                            </div>
                                        </div>
                                    </div>
                                    <div class="pull-right col-md-3">
                                        <button type="button" id="btnSearchAdminUser" name="Search" class="ladda-button btneffect">Search</button>&nbsp;
                                        <button type="button" id="btnClearAdminUser" name="Clear" class="ladda-button btneffect">Clear</button>&nbsp;
                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </form>

                <div class="row">
                    <div class="col-xs-12 col-sm-10 col-md-10 col-lg-12" id="adminUser_div">
                        <div class="table-responsive" id="divAdminUserList">
                            @Html.Partial("_AdminUserWebGrid", Model)
                        </div>
                    </div>
                </div>


            </div>
        </div>

    </div>
</div>


<script>

    $('#btnSearchAdminUser').click(function () {

        BindAdminUserList();
    });

    var jq = $.noConflict();

    jq(document).ready(function () {
        //jq('#UserTypeIds').multiselect({
        //    numberdisplayed: 1,
        //    //buttonwidth: '100%',
        //    maxheight: 150,
        //    includeselectalloption: true,
        //    enableClickableOptGroups: true

        //});
    });

    $('#btnClearAdminUser').click(function () {
        $("#txtSearchFirstName").val('');
        $("#txtSearchLastName").val('');
        $("#txtSearchUserName").val('');
        $("#UserTypeIds").val('');
        BindAdminUserList();
    });

    function BindAdminUserList() {

        var firstName = $("#txtSearchFirstName").val().trim();
        var lastName = $("#txtSearchLastName").val().trim();
        var username = $("#txtSearchUserName").val().trim();
        var UserType = $("#UserTypeIds").val();
        //var pagesize = $("#ddlpagesize").val().trim();
        //var pagesize = $("#ddlpagesize").val().trim();
        var pagesize = 50;
        if (pagesize == "" || pagesize == undefined || pagesize == "0") {
            pagesize = '@System.Configuration.ConfigurationManager.AppSettings["PageSize"]';
        }

        $("#modalWindow,#ui-loader").show();
        var Liveurl = '@System.Configuration.ConfigurationManager.AppSettings["LivesubURL"]';
        Liveurl = "/" + Liveurl + "AdminUser/AdminUserListPagingSortingList";

        $.ajax({
            type: "POST",
            url: Liveurl,
            data: { firstName: firstName, lastName: lastName, username: username, UserType: UserType, pagesize: pagesize, pageindex: "", columnName: "", sortorder: "" },
            dataType: "html",
            success: function (data) {
                $("#divAdminUserList").html('');
                $("#divAdminUserList").html(data + "&nbsp;");
                $("#modalWindow,#ui-loader").hide();

            }
        });
    }
   
</script>

EmployeeDirectory/Views/AdminUser/CreateAdminUser.cshtml
@model EmployeeDirectory.Models.AdminUserModel

@{
    ViewBag.Title = "CreateAdminUser";
}

<script src="~/js/bootstrap-multiselect.js"></script>
<link href="~/css/bootstrap-multiselect.css" rel="stylesheet" />

<style>
    .multiselect.dropdown-toggle.btn.btn-default {
        /*margin-right: 5px;*/
        max-width: 130px;
        overflow: hidden;
    }

    .dropdown-menu {
        max-height: 158px;
        overflow: auto;
    }
</style>



<div class="container-fluid">
    <br />
    @if (ViewBag.ErrorMessage != "" && ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger">
            @ViewBag.ErrorMessage
        </div>
    }

    @using (Html.BeginForm("CreateAdminUser", "AdminUser", FormMethod.Post, new { @id = "AdminUserForm", enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header" style="margin-bottom:20px;">
                        <h3 class="box-title">Add User</h3>
                    </div>
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">User Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.HiddenFor(m => m.ID)
                                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", @placeholder = "User Name", onblur = "UpdateEmailId(this);" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">First Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder = "First Name" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Last Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "Last Name" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Email <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email ID" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">User Type</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.DropDownListFor(m => m.UserTypeIds, ViewBag.UserTypeList as List<SelectListItem>, new { @class = "form-control selectmultidata", @multiple = "multiple" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Group Name</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.DropDownListFor(m => m.GroupId, ViewBag.GroupMasterList as List<SelectListItem>, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">&nbsp;</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-6">
                                    <div class="checkbox">
                                        <label>
                                            @Html.CheckBoxFor(m => m.IsLocked, new { @class = "checkbox" })Is Locked?
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="footer-header">
                        <div class="col-xs-12">

                            @Html.HiddenFor(m => m.ID)
                            <div class="col-xs-4 pull-right">
                                <button type="submit" class="col-xs-6 btneffect pull-right ">Submit</button>
                                <a title="" href="~/AdminUser/AdminUserList" class="col-xs-6 btneffect pull-right">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }

</div>



<script>

  

    var jq = $.noConflict();

    jq(document).ready(function () {
        jq('#UserTypeIds').multiselect({
            numberdisplayed: 1,
            //buttonwidth: '100%',
            maxheight: 150,
            includeselectalloption: true,
            enableClickableOptGroups: true

        });
    });

    function UpdateEmailId(ctl) {
        $('#Email').val(ctl.value + "@@hcsgcorp.com");
    }
</script>

EmployeeDirectory/Views/AdminUser/EditAdminUser.cshtml
@model EmployeeDirectory.Models.AdminUserModel

@{
    ViewBag.Title = "EditAdminUser";
}


<script src="~/js/bootstrap-multiselect.js"></script>
<link href="~/css/bootstrap-multiselect.css" rel="stylesheet" />

<style>
    .multiselect.dropdown-toggle.btn.btn-default {
        /*margin-right: 5px;*/
        max-width: 130px;
        overflow: hidden;
    }

    .dropdown-menu {
        max-height: 158px;
        overflow: auto;
    }
</style>


<div class="container-fluid">
    <br />
    @if (ViewBag.ErrorMessage != "" && ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger">
            @ViewBag.ErrorMessage
        </div>
    }

    @using (Html.BeginForm("EditAdminUser", "AdminUser", FormMethod.Post, new { @id = "AdminUserForm", enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header" style="margin-bottom:20px;">
                        <h3 class="box-title">Edit User</h3>
                    </div>
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">User Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.HiddenFor(m => m.ID)
                                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", @placeholder = "User Name", @readonly = "readonly" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">First Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder = "First Name" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Last Name <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "Last Name" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Email <span style="color:red;">*</span></label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email ID" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">User Type </label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-3">
                                    @Html.DropDownListFor(m => m.UserTypeIds, ViewBag.UserTypeList as List<SelectListItem>, new { @class = "form-control selectmultidata", @multiple = "multiple", @size = 10 })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">Group Name</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-4">
                                    @Html.DropDownListFor(m => m.GroupId, ViewBag.GroupMasterList as List<SelectListItem>, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">&nbsp;</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-6">
                                    <div class="checkbox">
                                        <label>
                                            @Html.CheckBoxFor(m => m.IsLocked, new { @class = "checkbox" })Is Locked?
                                        </label>
                                    </div>
                                </div>
                            </div>
                            @*<div class="form-group">
                                <label for="inputEmail" class="control-label col-xs-12 col-sm-2 col-md-2 col-lg-2">&nbsp;</label>
                                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
                                    
                                        <button type="submit" class="btn btn-default btn-primary">Update</button>
                                    
                                    <button type="reset" class="btn btn-default btn-danger" onclick="@("window.location.href='" + @Url.Action("AdminUserList", "AdminUser") + "'");">Cancel</button>
                                </div>
                            </div>*@
                        </div>
                    </div>
                    <div class="footer-header">
                        <div class="col-xs-12">

                            @Html.HiddenFor(m => m.ID)
                            <div class="col-xs-4 pull-right">
                                
                                
                                        <button type="submit" class="col-xs-6 btneffect pull-right">Update</button>
                                
                                <a class="col-xs-6 btneffect pull-right" href="~/AdminUser/AdminUserList">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>


<script>

    var jq = $.noConflict();

    jq(document).ready(function () {
        jq('#UserTypeIds').multiselect({
            numberdisplayed: 1,
            //buttonwidth: '100%',
            maxheight: 150,
            includeselectalloption: true,
            enableClickableOptGroups: true

        });

        var ccControl = '@Model.UserType';
        var ccValueList = new Array;
        ccValueList = ccControl.split(',');
        for (var i = 0; i < ccValueList.length; i++) {
            if (!$('#UserTypeIds').closest('div').find('.dropdown-menu').find('li').find('input[value=' + ccValueList[i] + ']').is(':checked')) {
                $('#UserTypeIds').closest('div').find('.dropdown-menu').find('li').find('input[value=' + ccValueList[i] + ']').click();
            }

        }
    });

   

</script>



