EmployeeDirectory/Controllers/UserTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EmployeeDirectory.Business;
using EmployeeDirectory.Entity;
using EmployeeDirectory.Helper;

namespace EmployeeDirectory.Controllers
{
    public class UserTypeController : BaseController
    {
        [Authorization(ScreenAlias.UserType, Rights.View, true)]
        public ActionResult UserTypeList()
        {
            var permission = CommonMethods.CheckPermission(StringEnum.GetStringValue(ScreenAlias.UserType));
            if (permission != null)
            {
                ViewBag.IsAdd = CommonMethods.GetFormPermission(permission).IsAdd;
                ViewBag.IsEdit = CommonMethods.GetFormPermission(permission).IsEdit;
                ViewBag.IsDelete = CommonMethods.GetFormPermission(permission).IsDelete;
            }

            UserTypeEntity objUserTypeEntity = new UserTypeEntity();
            List<UserTypeEntity> List = new List<UserTypeEntity>();
            UserTypeBusiness objUserTypeBusiness = new UserTypeBusiness();

            int[] paggingArray = Helper.HelperCls.GetDisplayRecordCount(ConfigurationProvider.Pageindex, ConfigurationProvider.WegGridPageSize);
            List<UserTypeEntity> list = objUserTypeBusiness.GetHSGUserTypeList("", "", paggingArray[0], paggingArray[1], "", "");
            for (int i = 0; i < list.Count; i++)
            {
                list[i].Pageindex = Convert.ToInt32(ConfigurationProvider.Pageindex);
            }

            objUserTypeEntity.UserTypeEntityList = list;

            return View(objUserTypeEntity);
        }

        [HttpPost]
        public ActionResult SaveUserType(UserTypeEntity model)
        {

            UserTypeBusiness objUserTypeBusiness = new UserTypeBusiness();
            int ans = 0;
            try
            {
                //model.UserId = SessionManager.UserID;
                //model.UserName = SessionManager.UserName;
                ans = objUserTypeBusiness.SaveUserType(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while processing your request. Please try again later";
            }
            return RedirectToAction("UserTypeList");
        }

        [Authorization(ScreenAlias.UserType, Rights.Edit, true)]
        public ActionResult EditUserType(int ID)
        {

            UserTypeEntity objUserTypeEntity = new UserTypeEntity();
            UserTypeBusiness objUserTypeBusiness = new UserTypeBusiness();
            try
            {

                objUserTypeEntity = objUserTypeBusiness.GetUserTypeDetailById(ID);

            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while processing your request. Please try again later";
            }

            return View(objUserTypeEntity);
        }

        [Authorization(ScreenAlias.UserType, Rights.Delete, true)]
        public ActionResult DeleteUserType(int ID)
        {

            UserTypeEntity objUserTypeEntity = new UserTypeEntity();
            UserTypeBusiness objUserTypeBusiness = new UserTypeBusiness();
            try
            {

                int ans = objUserTypeBusiness.DeleteUserType(ID);

            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while processing your request. Please try again later";
            }

            return RedirectToAction("UserTypeList");
        }

        public ActionResult GetAllUserTypeList()
        {

            UserTypeEntity objUserTypeEntity = new UserTypeEntity();
            UserTypeBusiness objUserTypeBusiness = new UserTypeBusiness();
            try
            {
                objUserTypeEntity.UserTypeEntityList = objUserTypeBusiness.GetAllUserTypeList();

            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while processing your request. Please try again later";
            }

            return Json(objUserTypeEntity.UserTypeEntityList, JsonRequestBehavior.AllowGet);
        }

    }
}

EmployeeDirectory/Views/UserType/EditUserType.cshtml
@model EmployeeDirectory.Entity.UserTypeEntity

@{
    Layout = null;
}

<!DOCTYPE html>

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Edit User Type</h4>
        </div>
        @using (Html.BeginForm("SaveUserType", "UserType", FormMethod.Post, new { @id = "FormUserType", @class = "validation-form-container row-fluid form-horizontal" }))
        {
            @Html.ValidationSummary(true)
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Name <span style="color:red;">*</span></label>
                        <div class="col-sm-9 control-label">
                            @Html.TextBoxFor(m => m.Name, new { @style = "float: left;" })
                            @Html.ValidationMessageFor(m => m.Name)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Description</label>
                        <div class="col-sm-9 control-label">
                            @Html.TextAreaFor(m => m.Description, new { @style = "float: left;" })
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Is Active?</label>
                        <div class="col-sm-1 control-label">
                            @Html.CheckBoxFor(m => m.IsActive, new { @style = "float: left;" })
                        </div>
                    </div>

                </div>

            </div>
            <div class="modal-footer">
                @Html.HiddenFor(m => m.ID)
                <button type="submit" class="btneffect pull-right">Update</button>
                <button type="button" class="btneffect pull-right" data-dismiss="modal">Close</button>
                <input type="hidden" id="trindex" />
            </div>
        }
    </div>
</div>

EmployeeDirectory/Views/UserType/UserTypeList.cshtml
@model EmployeeDirectory.Entity.UserTypeEntity

@{
    ViewBag.Title = "UserTypeList";
}



<div class="container-fluid">
    <br />
    <div class="row">
        <div class="box-header">
            <div class="col-sm-5 col-xs-12">
                <h3 class="box-title">  User Type List</h3>
            </div>
            @if (ViewBag.IsAdd != null)
            {
                if (ViewBag.IsAdd)
                {

                    <div class="col-sm-7 col-xs-12">
                        <a class="pull-right btneffect AdminUserAdd" id="btnAddUserType" onclick="AddUserType()" name="Add">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Add
                        </a>
                    </div>
                }
            }
        </div>

        <div class="container-fluid">
            <div class="row">
                <form role="form" id="AdminUserList" class="form-horizontal">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                        <div class="form-group">
                            <div class="table-responsive" id="divUserList">
                                @Html.Partial("_UserTypeList", Model.UserTypeEntityList)
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>


<div class="modal-dialog" id="AdditionalDialog" style="display:none;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Add User Type</h4>
        </div>
        @using (Html.BeginForm("SaveUserType", "UserType", FormMethod.Post, new { @id = "FormUserType", @class = "validation-form-container row-fluid form-horizontal" }))
        {
            @Html.ValidationSummary(true)
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Name <span style="color:red;">*</span></label>
                        <div class="col-sm-9 control-label">
                            @Html.TextBoxFor(m => m.Name, new { @style = "float: left;" })
                            @Html.ValidationMessageFor(m => m.Name)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Description</label>
                        <div class="col-sm-9 control-label">
                            @Html.TextAreaFor(m => m.Description, new { @style = "float: left;" })
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="exampleInputFile" class="col-sm-3 control-label">Is Active?</label>
                        <div class="col-sm-1 control-label">
                            @Html.CheckBoxFor(m => m.IsActive, new { @style = "float: left;" })
                        </div>
                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btneffect pull-right ladda-button">Save</button>
                <button type="button" class="btneffect pull-right ladda-button" data-dismiss="modal">Close</button>
                <input type="hidden" id="trindex" />
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        //$.validator.unobtrusive.parse("FormGroup");
        $('#FormUserType').find('#IsActive').attr('checked', true);
    })


    function AddUserType() {
        $("#parentModal").html($("#AdditionalDialog").clone().show()).modal('show');
    }


    $('#FormUserType').live('submit', function () {

        var Name = $(this).find('#Name').val().trim();

        if (Name == '') {
            $(this).find('#Name').css('border', 'red 1px solid');
            return false;

        }



    });
</script>

EmployeeDirectory/Views/UserType/_UserTypeList.cshtml
@model List<EmployeeDirectory.Entity.UserTypeEntity>

@{
    var gdUserTypeList = new WebGrid(Model, canPage: false, canSort: false, rowsPerPage: 10, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
}

<div>
    @gdUserTypeList.GetHtml(tableStyle: "webgrid",
                headerStyle: "webgrid-header",
                footerStyle: "webgrid-footer",
                htmlAttributes: new { Id = "tblUserList" },
                alternatingRowStyle: "webgrid-alternating-row",
                selectedRowStyle: "webgrid-selected-row",
                rowStyle: "webgrid-row-style",
                mode: WebGridPagerModes.Numeric,
                                columns: gdUserTypeList.Columns(
                                gdUserTypeList.Column("Name", "Group Name"),
                                gdUserTypeList.Column("Description", "Description"),
                                gdUserTypeList.Column("Action", format: @<text>
                            @if (ViewBag.IsEdit != null)
                                {
                                    if (ViewBag.IsEdit)
                                    {

                                        <a href="#" onclick="EditUserTypeList(@item.ID)"><i class="fa fa-edit"></i></a>
                                    }
                                }
                            @if (ViewBag.IsDelete != null)
                            {
                                if (ViewBag.IsDelete)
                                {

                                    <a href="~/UserType/DeleteUserType/@item.ID" onclick="return confirm('Are you sure you wish to delete this User Type?');"><i class="fa fa-trash"></i></a>
                                }
                            }
                        </text>, style: "webgrid-action-column")
                                                                                ))

</div>

<script>

    function EditUserTypeList(me) {
        $("#modalWindow,#ui-loader").show();

        var Liveurl = '@System.Configuration.ConfigurationManager.AppSettings["LivesubURL"]';
        Liveurl = "/" + Liveurl + "UserType/EditUserType";

        $.ajax({
            url: Liveurl,
            type: "GET",
            data: { Id: me },
            success: function (result) {
                $("#parentModal").html(result).modal('show');
                $("#modalWindow,#ui-loader").hide();
            }
        });


    }

</script>
